### ISSUE TITLE
Running experiments on MacOS

### ISSUE THREAD

**Issue by 610v4nn1** [angelajiang/SelectiveBackprop#1]
I have been trying to run your code on MacOS, and initially I had troubles because I was using python 3.8. After downgrading to python 3.6, I made some progress, but I still get an error when running train.py

The command I am using is: ```train.py --dataset cifar10 --model resnet18 --data_augmentation --cutout --length 16```

and the error is:

```
    if platform.system() == 'Windows':
AttributeError: module 'platform' has no attribute 'system'
```

I tried to replace it with uname().system but I face some other issues.
Can you please provide a list of the requirements with their corresponding versions?

Thanks.

**Comment by angelajiang** [comment]
I was unable to reproduce your error with MacOS and python3.6.

I had previously tested train.py on Linux with python2.7. I pushed an update so that train.py now works with python3. It works on MacOS 10.12.6 without cuda and Linux with python3.6 and python3.7.

**Comment by 610v4nn1** [comment]
Now it seems to work and it works also in AWS SageMaker notebooks.
Thanks!

```
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to data/cifar-10-python.tar.gz
171MB [00:08, 19.2MB/s]                                                         
Files already downloaded and verified
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
/home/ec2-user/SageMaker/SelectiveBackprop/lib/backproppers.py:55: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax_outputs = nn.Softmax()(outputs)             # OPT: not necessary when logging is off
============ EPOCH 0 ============
FPs: 50000 / 50000
BPs: 50000 / 50000
Test loss: 0.013189
Test acc: 37.550 
Time elapsed: 167.08s
============ EPOCH 1 ============
FPs: 100000 / 100000
BPs: 100000 / 100000
Test loss: 0.011481
Test acc: 45.730 
Time elapsed: 257.36s
============ EPOCH 2 ============
FPs: 150000 / 150000
BPs: 150000 / 150000
Test loss: 0.010276
Test acc: 52.480 
Time elapsed: 347.86s
```
